require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ScoreTrackersController do

  # This should return the minimal set of attributes required to create a valid
  # ScoreTracker. As you add validations to ScoreTracker, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all score_trackers as @score_trackers" do
      score_tracker = ScoreTracker.create! valid_attributes
      get :index
      assigns(:score_trackers).should eq([score_tracker])
    end
  end

  describe "GET show" do
    it "assigns the requested score_tracker as @score_tracker" do
      score_tracker = ScoreTracker.create! valid_attributes
      get :show, :id => score_tracker.id.to_s
      assigns(:score_tracker).should eq(score_tracker)
    end
  end

  describe "GET new" do
    it "assigns a new score_tracker as @score_tracker" do
      get :new
      assigns(:score_tracker).should be_a_new(ScoreTracker)
    end
  end

  describe "GET edit" do
    it "assigns the requested score_tracker as @score_tracker" do
      score_tracker = ScoreTracker.create! valid_attributes
      get :edit, :id => score_tracker.id.to_s
      assigns(:score_tracker).should eq(score_tracker)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ScoreTracker" do
        expect {
          post :create, :score_tracker => valid_attributes
        }.to change(ScoreTracker, :count).by(1)
      end

      it "assigns a newly created score_tracker as @score_tracker" do
        post :create, :score_tracker => valid_attributes
        assigns(:score_tracker).should be_a(ScoreTracker)
        assigns(:score_tracker).should be_persisted
      end

      it "redirects to the created score_tracker" do
        post :create, :score_tracker => valid_attributes
        response.should redirect_to(ScoreTracker.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved score_tracker as @score_tracker" do
        # Trigger the behavior that occurs when invalid params are submitted
        ScoreTracker.any_instance.stub(:save).and_return(false)
        post :create, :score_tracker => {}
        assigns(:score_tracker).should be_a_new(ScoreTracker)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ScoreTracker.any_instance.stub(:save).and_return(false)
        post :create, :score_tracker => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested score_tracker" do
        score_tracker = ScoreTracker.create! valid_attributes
        # Assuming there are no other score_trackers in the database, this
        # specifies that the ScoreTracker created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ScoreTracker.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => score_tracker.id, :score_tracker => {'these' => 'params'}
      end

      it "assigns the requested score_tracker as @score_tracker" do
        score_tracker = ScoreTracker.create! valid_attributes
        put :update, :id => score_tracker.id, :score_tracker => valid_attributes
        assigns(:score_tracker).should eq(score_tracker)
      end

      it "redirects to the score_tracker" do
        score_tracker = ScoreTracker.create! valid_attributes
        put :update, :id => score_tracker.id, :score_tracker => valid_attributes
        response.should redirect_to(score_tracker)
      end
    end

    describe "with invalid params" do
      it "assigns the score_tracker as @score_tracker" do
        score_tracker = ScoreTracker.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ScoreTracker.any_instance.stub(:save).and_return(false)
        put :update, :id => score_tracker.id.to_s, :score_tracker => {}
        assigns(:score_tracker).should eq(score_tracker)
      end

      it "re-renders the 'edit' template" do
        score_tracker = ScoreTracker.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ScoreTracker.any_instance.stub(:save).and_return(false)
        put :update, :id => score_tracker.id.to_s, :score_tracker => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested score_tracker" do
      score_tracker = ScoreTracker.create! valid_attributes
      expect {
        delete :destroy, :id => score_tracker.id.to_s
      }.to change(ScoreTracker, :count).by(-1)
    end

    it "redirects to the score_trackers list" do
      score_tracker = ScoreTracker.create! valid_attributes
      delete :destroy, :id => score_tracker.id.to_s
      response.should redirect_to(score_trackers_url)
    end
  end

end
